<a href="https://colab.research.google.com/github/sathishsivam/Java_conventional/blob/master/pandasintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x=np.random.randint(100,size=(4,3))

In [3]:
x

array([[86,  8, 45],
       [ 7, 32, 25],
       [47, 41, 32],
       [92, 34, 97]])

In [4]:
x.ndim

2

In [5]:
x[0]

array([86,  8, 45])

In [0]:
y=np.array([i for i in range(0,10)])

In [7]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y[0]

0

In [10]:
y[3]

3

In [0]:
import pandas as pd

In [0]:
x=pd.Series([i for i in range(0,10)],index=['a','b','c','d','e','f','g','h','i','j'],dtype=float)

In [22]:
x

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
i    8.0
j    9.0
dtype: float64

In [20]:
x['j']

9

In [16]:
x.dtype

dtype('int64')

In [0]:
data=pd.Series()

In [24]:
data


Series([], dtype: float64)

In [25]:
data.size


0

In [26]:
data.itemsize

8

In [27]:
data.ndim

1

In [28]:
data.nbytes

0

In [0]:

# How to make use of DataFrames

list of Dict

Dict of List





In [0]:
data=pd.DataFrame([[{"Name":"Haseena","Age":21,"City":"Salem"}],[{"Name":"Sindhu","Age":11,"City":"Salem"}]])

In [40]:
data

0
0  {'Name': 'Haseena', 'Age': 21, 'City': 'Salem'}
1   {'Name': 'Sindhu', 'Age': 11, 'City': 'Salem'}

In [0]:
data=pd.DataFrame({"Name":["Haseena","Sindhu","Arjun","Mani"],"Age":[21,32,12,13],"City":["Erode","Salem","Erode","Salem"]})


In [42]:
data

Age   City     Name
0   21  Erode  Haseena
1   32  Salem   Sindhu
2   12  Erode    Arjun
3   13  Salem     Mani

In [44]:
data["Name"]

0    Haseena
1     Sindhu
2      Arjun
3       Mani
Name: Name, dtype: object

In [0]:
data=pd.Series([1,2,3,4])

In [49]:
data

0    1
1    2
2    3
3    4
dtype: int64

In [0]:
# suppose if you wanna add the index explicitly

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])


In [53]:
data

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [54]:
data.dtype

dtype('int64')

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'],dtype=float) 


In [69]:
data

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64

In [70]:
data.values

array([1., 2., 3., 4., 5.])

In [71]:
data.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [0]:
data=pd.Series([1,2,3,4,5]) 

In [73]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [66]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [0]:
#A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])


In [76]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [78]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [79]:
data[0]

0.25

In [0]:
data[0]=12

In [81]:
data

0    12.00
1     0.50
2     0.75
3     1.00
dtype: float64

In [0]:
data[1]="Haseena"

In [83]:
data

0         12
1    Haseena
2       0.75
3          1
dtype: object

In [0]:
l=[1,"Haseena"]

In [86]:
l

[1, 'Haseena']

In [0]:
  data=pd.Series([i for i in range(0,20)])

In [92]:
data


0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int64

In [93]:
data

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
dtype: int64

In [96]:
data.ndim

1

In [97]:
data[0]

0

In [99]:
data[0:10:2]

0    0
2    2
4    4
6    6
8    8
dtype: int64

In [0]:
# this is the simple indexing which follows the python and declared the downward compatabilities

In [0]:
# Series as Dictionaries


In [0]:
city_population={"Salem":3427643,"Erode":2314234,"Coimbatore":4234234,"Tirusur":424234,"Ernakulam":3424234}

In [0]:
population=pd.Series(city_population)

In [105]:
population

Coimbatore    4234234
Ernakulam     3424234
Erode         2314234
Salem         3427643
Tirusur        424234
dtype: int64

In [0]:
population['Tirusur']=4343234

In [109]:
population

Coimbatore    4234234
Ernakulam     3424234
Erode         2314234
Salem         3427643
Tirusur       4343234
dtype: int64

In [110]:
population.values

array([4234234, 3424234, 2314234, 3427643, 4343234])

In [111]:
population.index


Index(['Coimbatore', 'Ernakulam', 'Erode', 'Salem', 'Tirusur'], dtype='object')

In [114]:
population.dtype

dtype('int64')

In [115]:
population

Coimbatore    4234234
Ernakulam     3424234
Erode         2314234
Salem         3427643
Tirusur       4343234
dtype: int64

In [116]:
population['Tirusur']

4343234

In [117]:
population.shape

(5,)