<a href="https://colab.research.google.com/github/sathishsivam/Java_conventional/blob/master/pandasintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x=np.random.randint(100,size=(4,3))

In [3]:
x

array([[53, 11, 61],
       [78, 89, 66],
       [35, 68, 27],
       [69, 73, 75]])

In [4]:
x.ndim

2

In [5]:
x[0]

array([53, 11, 61])

In [0]:
y=np.array([i for i in range(0,10)])

In [7]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y[0]

0

In [9]:
y[3]

3

In [0]:
import pandas as pd

In [0]:
x=pd.Series([i for i in range(0,10)],index=['a','b','c','d','e','f','g','h','i','j'],dtype=float)

In [12]:
x

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
i    8.0
j    9.0
dtype: float64

In [13]:
x['j']

9.0

In [14]:
x.dtype

dtype('float64')

In [0]:
data=pd.Series()

In [16]:
data


Series([], dtype: float64)

In [17]:
data.size


0

In [18]:
data.itemsize

8

In [19]:
data.ndim

1

In [20]:
data.nbytes

0

In [21]:

# How to make use of DataFrames

list of Dict

Dict of List





SyntaxError: ignored

In [0]:
data=pd.DataFrame([[{"Name":"Haseena","Age":21,"City":"Salem"}],[{"Name":"Sindhu","Age":11,"City":"Salem"}]])

In [0]:
data

In [0]:
data=pd.DataFrame({"Name":["Haseena","Sindhu","Arjun","Mani"],"Age":[21,32,12,13],"City":["Erode","Salem","Erode","Salem"]})


In [0]:
data

In [0]:
data["Name"]

In [0]:
data=pd.Series([1,2,3,4])

In [0]:
data

In [0]:
# suppose if you wanna add the index explicitly

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])


In [0]:
data

In [0]:
data.dtype

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'],dtype=float) 


In [0]:
data

In [0]:
data.values

In [0]:
data.index

In [0]:
data=pd.Series([1,2,3,4,5]) 

In [0]:
data

In [0]:
data.index

In [0]:
#A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])


In [0]:
data.index

In [0]:
data.values

In [0]:
data[0]

In [0]:
data[0]=12

In [0]:
data

In [0]:
data[1]="Haseena"

In [0]:
data

In [0]:
l=[1,"Haseena"]

In [0]:
l

In [0]:
  data=pd.Series([i for i in range(0,20)])

In [0]:
data


In [0]:
data

In [0]:
data.ndim

In [0]:
data[0]

In [0]:
data[0:10:2]

In [0]:
# this is the simple indexing which follows the python and declared the downward compatabilities

In [0]:
# Series as Dictionaries


In [0]:
city_population={"Salem":3427643,"Erode":2314234,"Coimbatore":4234234,"Tirusur":424234,"Ernakulam":3424234}

In [0]:
population=pd.Series(city_population)

In [0]:
population

In [0]:
population['Tirusur']=4343234

In [0]:
population

In [0]:
population.values

In [0]:
population.index


In [0]:
population.dtype

In [0]:
population

# New Section

In [0]:
population['Tirusur']

In [0]:
population.shape

In [0]:
x=pd.Series([1,2,3,4,5,6])

In [0]:
y=pd.Series([7,8,9,10,11,12])


In [24]:
x

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [25]:
y

0     7
1     8
2     9
3    10
4    11
5    12
dtype: int64

In [0]:
data=pd.DataFrame({"x":x,"y":y})

In [27]:
data

x   y
0  1   7
1  2   8
2  3   9
3  4  10
4  5  11
5  6  12

In [28]:
data['x']

0    1
1    2
2    3
3    4
4    5
5    6
Name: x, dtype: int64

In [29]:
data['y']

0     7
1     8
2     9
3    10
4    11
5    12
Name: y, dtype: int64

In [0]:
import numpy as np

In [0]:
data=pd.DataFrame({"A":np.random.randint(12,size=10),"B":np.random.randint(12,size=10)})

In [32]:
data

A  B
0   0  8
1   0  8
2  10  6
3   7  0
4  11  8
5   0  2
6   8  8
7   1  7
8   4  0
9   2  0

In [0]:
data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)])})

In [34]:
data

Age
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9

In [0]:
data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)]),"Height":pd.Series([i for i in range(0,11)])})

In [36]:
data

Age  Height
0   0.0       0
1   1.0       1
2   2.0       2
3   3.0       3
4   4.0       4
5   5.0       5
6   6.0       6
7   7.0       7
8   8.0       8
9   9.0       9
10  NaN      10

In [0]:
 data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)]),"Height":pd.Series([i for i in range(0,10)])})

In [38]:
data

Age  Height
0    0       0
1    1       1
2    2       2
3    3       3
4    4       4
5    5       5
6    6       6
7    7       7
8    8       8
9    9       9

In [0]:
data['Weight']=data['Age']+data['Height']

In [40]:
data

Age  Height  Weight
0    0       0       0
1    1       1       2
2    2       2       4
3    3       3       6
4    4       4       8
5    5       5      10
6    6       6      12
7    7       7      14
8    8       8      16
9    9       9      18

In [41]:
data['Height']

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Height, dtype: int64

In [42]:
data

Age  Height  Weight
0    0       0       0
1    1       1       2
2    2       2       4
3    3       3       6
4    4       4       8
5    5       5      10
6    6       6      12
7    7       7      14
8    8       8      16
9    9       9      18

In [43]:
data

Age  Height  Weight
0    0       0       0
1    1       1       2
2    2       2       4
3    3       3       6
4    4       4       8
5    5       5      10
6    6       6      12
7    7       7      14
8    8       8      16
9    9       9      18

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
Age       10 non-null int64
Height    10 non-null int64
Weight    10 non-null int64
dtypes: int64(3)
memory usage: 320.0 bytes


In [45]:
data['Age']

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Age, dtype: int64

In [46]:
data.Age

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Age, dtype: int64

In [47]:
data.Height

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
Name: Height, dtype: int64

In [50]:
data.Height is data['Height']


True

In [53]:
data.loc[0:3]

Age  Height  Weight
0    0       0       0
1    1       1       2
2    2       2       4
3    3       3       6