<a href="https://colab.research.google.com/github/sathishsivam/Java_conventional/blob/master/pandasintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
x=np.random.randint(100,size=(4,3))

In [0]:
x

array([[74, 23, 99],
       [85, 71, 26],
       [53, 48, 45],
       [37, 39, 40]])

In [0]:
x.ndim

2

In [0]:
x[0]

array([74, 23, 99])

In [0]:
y=np.array([i for i in range(0,10)])

In [0]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
y[0]

0

In [0]:
y[3]

3

In [0]:
import pandas as pd

In [0]:
x=pd.Series([i for i in range(0,10)],index=['a','b','c','d','e','f','g','h','i','j'],dtype=float)

In [0]:
x

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    5.0
g    6.0
h    7.0
i    8.0
j    9.0
dtype: float64

In [0]:
x['j']

9.0

In [0]:
x.dtype

dtype('float64')

In [0]:
data=pd.Series()

In [0]:
data


Series([], dtype: float64)

In [0]:
data.size


0

In [0]:
data.itemsize

8

In [0]:
data.ndim

1

In [0]:
data.nbytes

0

In [0]:

# How to make use of DataFrames

list of Dict

Dict of List





SyntaxError: ignored

In [0]:
data=pd.DataFrame([[{"Name":"Haseena","Age":21,"City":"Salem"}],[{"Name":"Sindhu","Age":11,"City":"Salem"}]])

In [0]:
data

In [0]:
data=pd.DataFrame({"Name":["Haseena","Sindhu","Arjun","Mani"],"Age":[21,32,12,13],"City":["Erode","Salem","Erode","Salem"]})


In [0]:
data

In [0]:
data["Name"]

In [0]:
data=pd.Series([1,2,3,4])

In [0]:
data

In [0]:
# suppose if you wanna add the index explicitly

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])


In [0]:
data

In [0]:
data.dtype

In [0]:
data=pd.Series([1,2,3,4,5], index=['a','b','c','d','e'],dtype=float) 


In [0]:
data

In [0]:
data.values

In [0]:
data.index

In [0]:
data=pd.Series([1,2,3,4,5]) 

In [0]:
data

In [0]:
data.index

In [0]:
#A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])


In [0]:
data.index

In [0]:
data.values

In [0]:
data[0]

In [0]:
data[0]=12

In [0]:
data

In [0]:
data[1]="Haseena"

In [0]:
data

In [0]:
l=[1,"Haseena"]

In [0]:
l

In [0]:
  data=pd.Series([i for i in range(0,20)])

In [0]:
data


In [0]:
data

In [0]:
data.ndim

In [0]:
data[0]

In [0]:
data[0:10:2]

In [0]:
# this is the simple indexing which follows the python and declared the downward compatabilities

In [0]:
# Series as Dictionaries


In [0]:
city_population={"Salem":3427643,"Erode":2314234,"Coimbatore":4234234,"Tirusur":424234,"Ernakulam":3424234}

In [0]:
population=pd.Series(city_population)

In [0]:
population

In [0]:
population['Tirusur']=4343234

In [0]:
population

In [0]:
population.values

In [0]:
population.index


In [0]:
population.dtype

In [0]:
population

# New Section

In [0]:
population['Tirusur']

In [0]:
population.shape

In [0]:
x=pd.Series([1,2,3,4,5,6])

In [0]:
y=pd.Series([7,8,9,10,11,12])


In [0]:
x

In [0]:
y

In [0]:
data=pd.DataFrame({"x":x,"y":y})

In [0]:
data

In [0]:
data['x']

In [0]:
data['y']

In [0]:
import numpy as np

In [0]:
data=pd.DataFrame({"A":np.random.randint(12,size=10),"B":np.random.randint(12,size=10)})

In [0]:
data

In [0]:
data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)])})

In [0]:
data

In [0]:
data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)]),"Height":pd.Series([i for i in range(0,11)])})

In [0]:
data

In [0]:
 data=pd.DataFrame({"Age":pd.Series([i for i in range(0,10)]),"Height":pd.Series([i for i in range(0,10)])})

In [0]:
data

In [0]:
data['Weight']=data['Age']+data['Height']

In [0]:
data

In [0]:
data['Height']

In [0]:
data

In [0]:
data

In [0]:
data.info()

In [0]:
data['Age']

In [0]:
data.Age

In [0]:
data.Height

In [0]:
data.Height is data['Height']


In [0]:
data.loc[0:3]